name: Create Bitbucket Pull Request

on:
  push:
    branches:
      - master

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request on Bitbucket
        env:
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.BITBUCKET_APP_PASSWORD }}
        run: |
          curl -X POST -u $BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD \
          -H "Content-Type: application/json" \
          -d '{
                "title": "New PR from GitHub Action",
                "source": {
                  "branch": {
                    "name": "master"
                  }
                },
                "destination": {
                  "branch": {
                    "name": "main"
                  }
                }
              }' \
          https://api.bitbucket.org/2.0/repositories/mingos/snap-templates/pullrequests
