name: Create Bitbucket Pull Request

on:
  push:
    branches:
      - master

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Bitbucket CLI
        run: |
          python -m pip install bitbucket-cli

      - name: Create Pull Request on Bitbucket
        env:
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.BITBUCKET_APP_PASSWORD }}
        run: |
          bb pullrequest create --title "New PR from GitHub Action" --source master --destination master --repo mingos/snap-templates/templates
